export const schema = {
  models: {
    User: {
      name: "User",
      fields: {
        id: {
          name: "id",
          isArray: false,
          type: "ID",
          isRequired: true,
          attributes: [],
        },
        email: {
          name: "email",
          isArray: false,
          type: "AWSEmail",
          isRequired: true,
          attributes: [],
        },
        name: {
          name: "name",
          isArray: false,
          type: "String",
          isRequired: true,
          attributes: [],
        },
        phoneNumber: {
          name: "phoneNumber",
          isArray: false,
          type: "AWSPhone",
          isRequired: false,
          attributes: [],
        },
        company: {
          name: "company",
          isArray: false,
          type: {
            model: "Company",
          },
          isRequired: false,
          attributes: [],
          association: {
            connectionType: "BELONGS_TO",
            targetName: "companyUsersId",
          },
        },
        profilePhoto: {
          name: "profilePhoto",
          isArray: false,
          type: "String",
          isRequired: false,
          attributes: [],
        },
        accessGroups: {
          name: "accessGroups",
          isArray: true,
          type: "String",
          isRequired: false,
          attributes: [],
          isArrayNullable: true,
        },
        createdAt: {
          name: "createdAt",
          isArray: false,
          type: "AWSDateTime",
          isRequired: false,
          attributes: [],
          isReadOnly: true,
        },
        updatedAt: {
          name: "updatedAt",
          isArray: false,
          type: "AWSDateTime",
          isRequired: false,
          attributes: [],
          isReadOnly: true,
        },
      },
      syncable: true,
      pluralName: "Users",
      attributes: [
        {
          type: "model",
          properties: {},
        },
        {
          type: "auth",
          properties: {
            rules: [
              {
                provider: "userPools",
                ownerField: "owner",
                allow: "owner",
                identityClaim: "cognito:username",
                operations: ["create", "update", "delete", "read"],
              },
              {
                groupClaim: "cognito:groups",
                provider: "userPools",
                allow: "groups",
                groups: ["Admin"],
                operations: ["create", "update", "delete", "read"],
              },
              {
                groupClaim: "cognito:groups",
                provider: "userPools",
                allow: "groups",
                groupsField: "accessGroups",
                groupField: "groups",
                operations: ["create", "update", "delete", "read"],
              },
            ],
          },
        },
      ],
    },
    Company: {
      name: "Company",
      fields: {
        id: {
          name: "id",
          isArray: false,
          type: "ID",
          isRequired: true,
          attributes: [],
        },
        name: {
          name: "name",
          isArray: false,
          type: "String",
          isRequired: true,
          attributes: [],
        },
        address: {
          name: "address",
          isArray: false,
          type: {
            model: "Address",
          },
          isRequired: false,
          attributes: [],
          association: {
            connectionType: "HAS_ONE",
            associatedWith: "id",
            targetName: "companyAddressId",
          },
        },
        users: {
          name: "users",
          isArray: true,
          type: {
            model: "User",
          },
          isRequired: false,
          attributes: [],
          isArrayNullable: true,
          association: {
            connectionType: "HAS_MANY",
            associatedWith: "companyUsersId",
          },
        },
        recipients: {
          name: "recipients",
          isArray: true,
          type: {
            model: "Recipient",
          },
          isRequired: false,
          attributes: [],
          isArrayNullable: true,
          association: {
            connectionType: "HAS_MANY",
            associatedWith: "companyRecipientsId",
          },
        },
        giftEventsByDate: {
          name: "giftEventsByDate",
          isArray: true,
          type: {
            model: "GiftEvent",
          },
          isRequired: false,
          attributes: [],
          isArrayNullable: true,
          association: {
            connectionType: "HAS_MANY",
            associatedWith: "companyID",
          },
        },
        accessGroups: {
          name: "accessGroups",
          isArray: true,
          type: "String",
          isRequired: false,
          attributes: [],
          isArrayNullable: true,
        },
        createdAt: {
          name: "createdAt",
          isArray: false,
          type: "AWSDateTime",
          isRequired: false,
          attributes: [],
          isReadOnly: true,
        },
        updatedAt: {
          name: "updatedAt",
          isArray: false,
          type: "AWSDateTime",
          isRequired: false,
          attributes: [],
          isReadOnly: true,
        },
        companyAddressId: {
          name: "companyAddressId",
          isArray: false,
          type: "ID",
          isRequired: false,
          attributes: [],
        },
      },
      syncable: true,
      pluralName: "Companies",
      attributes: [
        {
          type: "model",
          properties: {},
        },
        {
          type: "auth",
          properties: {
            rules: [
              {
                provider: "userPools",
                ownerField: "owner",
                allow: "owner",
                identityClaim: "cognito:username",
                operations: ["create", "update", "delete", "read"],
              },
              {
                groupClaim: "cognito:groups",
                provider: "userPools",
                allow: "groups",
                groups: ["Admin"],
                operations: ["create", "update", "delete", "read"],
              },
              {
                groupClaim: "cognito:groups",
                provider: "userPools",
                allow: "groups",
                groupsField: "accessGroups",
                groupField: "groups",
                operations: ["create", "update", "delete", "read"],
              },
            ],
          },
        },
      ],
    },
    Address: {
      name: "Address",
      fields: {
        id: {
          name: "id",
          isArray: false,
          type: "ID",
          isRequired: true,
          attributes: [],
        },
        address1: {
          name: "address1",
          isArray: false,
          type: "String",
          isRequired: true,
          attributes: [],
        },
        address2: {
          name: "address2",
          isArray: false,
          type: "String",
          isRequired: false,
          attributes: [],
        },
        city: {
          name: "city",
          isArray: false,
          type: "String",
          isRequired: false,
          attributes: [],
        },
        state: {
          name: "state",
          isArray: false,
          type: "String",
          isRequired: false,
          attributes: [],
        },
        zip: {
          name: "zip",
          isArray: false,
          type: "String",
          isRequired: true,
          attributes: [],
        },
        accessGroups: {
          name: "accessGroups",
          isArray: true,
          type: "String",
          isRequired: false,
          attributes: [],
          isArrayNullable: true,
        },
        createdAt: {
          name: "createdAt",
          isArray: false,
          type: "AWSDateTime",
          isRequired: false,
          attributes: [],
          isReadOnly: true,
        },
        updatedAt: {
          name: "updatedAt",
          isArray: false,
          type: "AWSDateTime",
          isRequired: false,
          attributes: [],
          isReadOnly: true,
        },
      },
      syncable: true,
      pluralName: "Addresses",
      attributes: [
        {
          type: "model",
          properties: {},
        },
        {
          type: "auth",
          properties: {
            rules: [
              {
                provider: "userPools",
                ownerField: "owner",
                allow: "owner",
                identityClaim: "cognito:username",
                operations: ["create", "update", "delete", "read"],
              },
              {
                groupClaim: "cognito:groups",
                provider: "userPools",
                allow: "groups",
                groups: ["Admin"],
                operations: ["create", "update", "delete", "read"],
              },
              {
                groupClaim: "cognito:groups",
                provider: "userPools",
                allow: "groups",
                groupsField: "accessGroups",
                groupField: "groups",
                operations: ["create", "update", "delete", "read"],
              },
            ],
          },
        },
      ],
    },
    Recipient: {
      name: "Recipient",
      fields: {
        id: {
          name: "id",
          isArray: false,
          type: "ID",
          isRequired: true,
          attributes: [],
        },
        company: {
          name: "company",
          isArray: false,
          type: {
            model: "Company",
          },
          isRequired: false,
          attributes: [],
          association: {
            connectionType: "BELONGS_TO",
            targetName: "companyRecipientsId",
          },
        },
        recipientType: {
          name: "recipientType",
          isArray: false,
          type: "String",
          isRequired: false,
          attributes: [],
        },
        firstName: {
          name: "firstName",
          isArray: false,
          type: "String",
          isRequired: false,
          attributes: [],
        },
        lastName: {
          name: "lastName",
          isArray: false,
          type: "String",
          isRequired: false,
          attributes: [],
        },
        shippingAddress: {
          name: "shippingAddress",
          isArray: false,
          type: {
            model: "Address",
          },
          isRequired: false,
          attributes: [],
          association: {
            connectionType: "HAS_ONE",
            associatedWith: "id",
            targetName: "recipientShippingAddressId",
          },
        },
        email: {
          name: "email",
          isArray: false,
          type: "AWSEmail",
          isRequired: false,
          attributes: [],
        },
        phone: {
          name: "phone",
          isArray: false,
          type: "AWSPhone",
          isRequired: false,
          attributes: [],
        },
        jobTitle: {
          name: "jobTitle",
          isArray: false,
          type: "String",
          isRequired: false,
          attributes: [],
        },
        birthday: {
          name: "birthday",
          isArray: false,
          type: "AWSDate",
          isRequired: false,
          attributes: [],
        },
        startDate: {
          name: "startDate",
          isArray: false,
          type: "AWSDate",
          isRequired: false,
          attributes: [],
        },
        departmentID: {
          name: "departmentID",
          isArray: false,
          type: "ID",
          isRequired: false,
          attributes: [],
        },
        profilePhoto: {
          name: "profilePhoto",
          isArray: false,
          type: "String",
          isRequired: false,
          attributes: [],
        },
        favorites: {
          name: "favorites",
          isArray: true,
          type: {
            model: "ProfileFavorite",
          },
          isRequired: false,
          attributes: [],
          isArrayNullable: true,
          association: {
            connectionType: "HAS_MANY",
            associatedWith: "recipientFavoritesId",
          },
        },
        giftHistory: {
          name: "giftHistory",
          isArray: true,
          type: {
            model: "GiftEvent",
          },
          isRequired: false,
          attributes: [],
          isArrayNullable: true,
          association: {
            connectionType: "HAS_MANY",
            associatedWith: "recipient",
          },
        },
        welcomed: {
          name: "welcomed",
          isArray: false,
          type: "AWSDateTime",
          isRequired: false,
          attributes: [],
        },
        accessGroups: {
          name: "accessGroups",
          isArray: true,
          type: "String",
          isRequired: false,
          attributes: [],
          isArrayNullable: true,
        },
        createdAt: {
          name: "createdAt",
          isArray: false,
          type: "AWSDateTime",
          isRequired: false,
          attributes: [],
          isReadOnly: true,
        },
        updatedAt: {
          name: "updatedAt",
          isArray: false,
          type: "AWSDateTime",
          isRequired: false,
          attributes: [],
          isReadOnly: true,
        },
        recipientShippingAddressId: {
          name: "recipientShippingAddressId",
          isArray: false,
          type: "ID",
          isRequired: false,
          attributes: [],
        },
      },
      syncable: true,
      pluralName: "Recipients",
      attributes: [
        {
          type: "model",
          properties: {},
        },
        {
          type: "key",
          properties: {
            name: "byDepartment",
            fields: ["departmentID", "firstName", "lastName"],
          },
        },
        {
          type: "auth",
          properties: {
            rules: [
              {
                provider: "userPools",
                ownerField: "owner",
                allow: "owner",
                identityClaim: "cognito:username",
                operations: ["create", "update", "delete", "read"],
              },
              {
                groupClaim: "cognito:groups",
                provider: "userPools",
                allow: "groups",
                groups: ["Admin"],
                operations: ["create", "update", "delete", "read"],
              },
              {
                groupClaim: "cognito:groups",
                provider: "userPools",
                allow: "groups",
                groupsField: "accessGroups",
                groupField: "groups",
                operations: ["create", "update", "delete", "read"],
              },
            ],
          },
        },
      ],
    },
    ProfileFavorite: {
      name: "ProfileFavorite",
      fields: {
        id: {
          name: "id",
          isArray: false,
          type: "ID",
          isRequired: true,
          attributes: [],
        },
        type: {
          name: "type",
          isArray: false,
          type: "String",
          isRequired: false,
          attributes: [],
        },
        value: {
          name: "value",
          isArray: false,
          type: "String",
          isRequired: false,
          attributes: [],
        },
        accessGroups: {
          name: "accessGroups",
          isArray: true,
          type: "String",
          isRequired: false,
          attributes: [],
          isArrayNullable: true,
        },
        createdAt: {
          name: "createdAt",
          isArray: false,
          type: "AWSDateTime",
          isRequired: false,
          attributes: [],
          isReadOnly: true,
        },
        updatedAt: {
          name: "updatedAt",
          isArray: false,
          type: "AWSDateTime",
          isRequired: false,
          attributes: [],
          isReadOnly: true,
        },
        recipientFavoritesId: {
          name: "recipientFavoritesId",
          isArray: false,
          type: "ID",
          isRequired: false,
          attributes: [],
        },
      },
      syncable: true,
      pluralName: "ProfileFavorites",
      attributes: [
        {
          type: "model",
          properties: {},
        },
        {
          type: "auth",
          properties: {
            rules: [
              {
                provider: "userPools",
                ownerField: "owner",
                allow: "owner",
                identityClaim: "cognito:username",
                operations: ["create", "update", "delete", "read"],
              },
              {
                groupClaim: "cognito:groups",
                provider: "userPools",
                allow: "groups",
                groups: ["Admin"],
                operations: ["create", "update", "delete", "read"],
              },
              {
                groupClaim: "cognito:groups",
                provider: "userPools",
                allow: "groups",
                groupsField: "accessGroups",
                groupField: "groups",
                operations: ["create", "update", "delete", "read"],
              },
            ],
          },
        },
      ],
    },
    GiftEvent: {
      name: "GiftEvent",
      fields: {
        id: {
          name: "id",
          isArray: false,
          type: "ID",
          isRequired: true,
          attributes: [],
        },
        companyID: {
          name: "companyID",
          isArray: false,
          type: "ID",
          isRequired: true,
          attributes: [],
        },
        orderID: {
          name: "orderID",
          isArray: false,
          type: "ID",
          isRequired: false,
          attributes: [],
        },
        recipient: {
          name: "recipient",
          isArray: false,
          type: {
            model: "Recipient",
          },
          isRequired: false,
          attributes: [],
          association: {
            connectionType: "BELONGS_TO",
            targetName: "recipientID",
          },
        },
        giftType: {
          name: "giftType",
          isArray: false,
          type: {
            enum: "GiftType",
          },
          isRequired: false,
          attributes: [],
        },
        dateType: {
          name: "dateType",
          isArray: false,
          type: {
            enum: "GiftDateType",
          },
          isRequired: false,
          attributes: [],
        },
        date: {
          name: "date",
          isArray: false,
          type: "AWSDate",
          isRequired: false,
          attributes: [],
        },
        gift: {
          name: "gift",
          isArray: false,
          type: {
            model: "Gift",
          },
          isRequired: true,
          attributes: [],
          association: {
            connectionType: "HAS_ONE",
            associatedWith: "id",
            targetName: "giftEventGiftId",
          },
        },
        finalPrice: {
          name: "finalPrice",
          isArray: false,
          type: "String",
          isRequired: false,
          attributes: [],
        },
        shippingCost: {
          name: "shippingCost",
          isArray: false,
          type: "String",
          isRequired: false,
          attributes: [],
        },
        fullfilled: {
          name: "fullfilled",
          isArray: false,
          type: "AWSDateTime",
          isRequired: false,
          attributes: [],
        },
        accessGroups: {
          name: "accessGroups",
          isArray: true,
          type: "String",
          isRequired: false,
          attributes: [],
          isArrayNullable: true,
        },
        createdAt: {
          name: "createdAt",
          isArray: false,
          type: "AWSDateTime",
          isRequired: false,
          attributes: [],
          isReadOnly: true,
        },
        updatedAt: {
          name: "updatedAt",
          isArray: false,
          type: "AWSDateTime",
          isRequired: false,
          attributes: [],
          isReadOnly: true,
        },
        giftEventGiftId: {
          name: "giftEventGiftId",
          isArray: false,
          type: "ID",
          isRequired: true,
          attributes: [],
        },
      },
      syncable: true,
      pluralName: "GiftEvents",
      attributes: [
        {
          type: "model",
          properties: {},
        },
        {
          type: "key",
          properties: {
            name: "byCompanyByDate",
            fields: ["companyID", "date"],
          },
        },
        {
          type: "key",
          properties: {
            name: "byRecipientByDate",
            fields: ["recipientID", "date"],
          },
        },
        {
          type: "key",
          properties: {
            name: "byOrder",
            fields: ["orderID", "date"],
          },
        },
        {
          type: "auth",
          properties: {
            rules: [
              {
                provider: "userPools",
                ownerField: "owner",
                allow: "owner",
                identityClaim: "cognito:username",
                operations: ["create", "update", "delete", "read"],
              },
              {
                groupClaim: "cognito:groups",
                provider: "userPools",
                allow: "groups",
                groups: ["Admin"],
                operations: ["create", "update", "delete", "read"],
              },
              {
                groupClaim: "cognito:groups",
                provider: "userPools",
                allow: "groups",
                groupsField: "accessGroups",
                groupField: "groups",
                operations: ["create", "update", "delete", "read"],
              },
            ],
          },
        },
      ],
    },
    Gift: {
      name: "Gift",
      fields: {
        id: {
          name: "id",
          isArray: false,
          type: "ID",
          isRequired: true,
          attributes: [],
        },
        name: {
          name: "name",
          isArray: false,
          type: "String",
          isRequired: true,
          attributes: [],
        },
        items: {
          name: "items",
          isArray: true,
          type: {
            model: "Item",
          },
          isRequired: false,
          attributes: [],
          isArrayNullable: true,
          association: {
            connectionType: "HAS_MANY",
            associatedWith: "giftItemsId",
          },
        },
        price: {
          name: "price",
          isArray: false,
          type: "String",
          isRequired: false,
          attributes: [],
        },
        description: {
          name: "description",
          isArray: false,
          type: "String",
          isRequired: false,
          attributes: [],
        },
        pictures: {
          name: "pictures",
          isArray: true,
          type: {
            model: "GiftImage",
          },
          isRequired: false,
          attributes: [],
          isArrayNullable: true,
          association: {
            connectionType: "HAS_MANY",
            associatedWith: "giftPicturesId",
          },
        },
        active: {
          name: "active",
          isArray: false,
          type: "Boolean",
          isRequired: false,
          attributes: [],
        },
        needs_subscription: {
          name: "needs_subscription",
          isArray: false,
          type: "Boolean",
          isRequired: false,
          attributes: [],
        },
        createdAt: {
          name: "createdAt",
          isArray: false,
          type: "AWSDateTime",
          isRequired: false,
          attributes: [],
          isReadOnly: true,
        },
        updatedAt: {
          name: "updatedAt",
          isArray: false,
          type: "AWSDateTime",
          isRequired: false,
          attributes: [],
          isReadOnly: true,
        },
      },
      syncable: true,
      pluralName: "Gifts",
      attributes: [
        {
          type: "model",
          properties: {},
        },
        {
          type: "auth",
          properties: {
            rules: [
              {
                groupClaim: "cognito:groups",
                provider: "userPools",
                allow: "groups",
                groups: ["Admin"],
                operations: ["create", "update", "delete", "read"],
              },
              {
                allow: "private",
                operations: ["read"],
              },
            ],
          },
        },
      ],
    },
    Item: {
      name: "Item",
      fields: {
        id: {
          name: "id",
          isArray: false,
          type: "ID",
          isRequired: true,
          attributes: [],
        },
        name: {
          name: "name",
          isArray: false,
          type: "String",
          isRequired: true,
          attributes: [],
        },
        description: {
          name: "description",
          isArray: false,
          type: "String",
          isRequired: false,
          attributes: [],
        },
        weight: {
          name: "weight",
          isArray: false,
          type: "String",
          isRequired: false,
          attributes: [],
        },
        price: {
          name: "price",
          isArray: false,
          type: "String",
          isRequired: false,
          attributes: [],
        },
        pictures: {
          name: "pictures",
          isArray: true,
          type: {
            model: "GiftImage",
          },
          isRequired: false,
          attributes: [],
          isArrayNullable: true,
          association: {
            connectionType: "HAS_MANY",
            associatedWith: "itemPicturesId",
          },
        },
        active: {
          name: "active",
          isArray: false,
          type: "Boolean",
          isRequired: false,
          attributes: [],
        },
        source: {
          name: "source",
          isArray: false,
          type: "String",
          isRequired: false,
          attributes: [],
        },
        brandingAvailable: {
          name: "brandingAvailable",
          isArray: false,
          type: "Boolean",
          isRequired: false,
          attributes: [],
        },
        quantityAvailable: {
          name: "quantityAvailable",
          isArray: false,
          type: "Int",
          isRequired: false,
          attributes: [],
        },
        createdAt: {
          name: "createdAt",
          isArray: false,
          type: "AWSDateTime",
          isRequired: false,
          attributes: [],
          isReadOnly: true,
        },
        updatedAt: {
          name: "updatedAt",
          isArray: false,
          type: "AWSDateTime",
          isRequired: false,
          attributes: [],
          isReadOnly: true,
        },
        giftItemsId: {
          name: "giftItemsId",
          isArray: false,
          type: "ID",
          isRequired: false,
          attributes: [],
        },
      },
      syncable: true,
      pluralName: "Items",
      attributes: [
        {
          type: "model",
          properties: {},
        },
        {
          type: "auth",
          properties: {
            rules: [
              {
                groupClaim: "cognito:groups",
                provider: "userPools",
                allow: "groups",
                groups: ["Admin"],
                operations: ["create", "update", "delete", "read"],
              },
              {
                allow: "private",
                operations: ["read"],
              },
            ],
          },
        },
      ],
    },
    GiftImage: {
      name: "GiftImage",
      fields: {
        id: {
          name: "id",
          isArray: false,
          type: "ID",
          isRequired: true,
          attributes: [],
        },
        alt: {
          name: "alt",
          isArray: false,
          type: "String",
          isRequired: true,
          attributes: [],
        },
        src: {
          name: "src",
          isArray: false,
          type: "String",
          isRequired: true,
          attributes: [],
        },
        createdAt: {
          name: "createdAt",
          isArray: false,
          type: "AWSDateTime",
          isRequired: false,
          attributes: [],
          isReadOnly: true,
        },
        updatedAt: {
          name: "updatedAt",
          isArray: false,
          type: "AWSDateTime",
          isRequired: false,
          attributes: [],
          isReadOnly: true,
        },
        giftPicturesId: {
          name: "giftPicturesId",
          isArray: false,
          type: "ID",
          isRequired: false,
          attributes: [],
        },
        itemPicturesId: {
          name: "itemPicturesId",
          isArray: false,
          type: "ID",
          isRequired: false,
          attributes: [],
        },
      },
      syncable: true,
      pluralName: "GiftImages",
      attributes: [
        {
          type: "model",
          properties: {},
        },
        {
          type: "auth",
          properties: {
            rules: [
              {
                groupClaim: "cognito:groups",
                provider: "userPools",
                allow: "groups",
                groups: ["Admin"],
                operations: ["create", "update", "delete", "read"],
              },
              {
                allow: "private",
                operations: ["read"],
              },
            ],
          },
        },
      ],
    },
    Department: {
      name: "Department",
      fields: {
        id: {
          name: "id",
          isArray: false,
          type: "ID",
          isRequired: true,
          attributes: [],
        },
        name: {
          name: "name",
          isArray: false,
          type: "String",
          isRequired: true,
          attributes: [],
        },
        recipients: {
          name: "recipients",
          isArray: true,
          type: {
            model: "Recipient",
          },
          isRequired: false,
          attributes: [],
          isArrayNullable: true,
          association: {
            connectionType: "HAS_MANY",
            associatedWith: "departmentID",
          },
        },
        accessGroups: {
          name: "accessGroups",
          isArray: true,
          type: "String",
          isRequired: false,
          attributes: [],
          isArrayNullable: true,
        },
        createdAt: {
          name: "createdAt",
          isArray: false,
          type: "AWSDateTime",
          isRequired: false,
          attributes: [],
          isReadOnly: true,
        },
        updatedAt: {
          name: "updatedAt",
          isArray: false,
          type: "AWSDateTime",
          isRequired: false,
          attributes: [],
          isReadOnly: true,
        },
      },
      syncable: true,
      pluralName: "Departments",
      attributes: [
        {
          type: "model",
          properties: {},
        },
        {
          type: "auth",
          properties: {
            rules: [
              {
                provider: "userPools",
                ownerField: "owner",
                allow: "owner",
                identityClaim: "cognito:username",
                operations: ["create", "update", "delete", "read"],
              },
              {
                groupClaim: "cognito:groups",
                provider: "userPools",
                allow: "groups",
                groups: ["Admin"],
                operations: ["create", "update", "delete", "read"],
              },
              {
                groupClaim: "cognito:groups",
                provider: "userPools",
                allow: "groups",
                groupsField: "accessGroups",
                groupField: "groups",
                operations: ["create", "update", "delete", "read"],
              },
            ],
          },
        },
      ],
    },
    Order: {
      name: "Order",
      fields: {
        id: {
          name: "id",
          isArray: false,
          type: "ID",
          isRequired: true,
          attributes: [],
        },
        name: {
          name: "name",
          isArray: false,
          type: "String",
          isRequired: true,
          attributes: [],
        },
        note: {
          name: "note",
          isArray: false,
          type: "String",
          isRequired: false,
          attributes: [],
        },
        giftEvents: {
          name: "giftEvents",
          isArray: true,
          type: {
            model: "GiftEvent",
          },
          isRequired: false,
          attributes: [],
          isArrayNullable: true,
          association: {
            connectionType: "HAS_MANY",
            associatedWith: "orderID",
          },
        },
        createdBy: {
          name: "createdBy",
          isArray: false,
          type: "String",
          isRequired: true,
          attributes: [],
        },
        totalPrice: {
          name: "totalPrice",
          isArray: false,
          type: "String",
          isRequired: false,
          attributes: [],
        },
        completed: {
          name: "completed",
          isArray: false,
          type: "AWSDateTime",
          isRequired: false,
          attributes: [],
        },
        orderType: {
          name: "orderType",
          isArray: false,
          type: {
            enum: "GiftType",
          },
          isRequired: false,
          attributes: [],
        },
        orderDateType: {
          name: "orderDateType",
          isArray: false,
          type: {
            enum: "GiftDateType",
          },
          isRequired: false,
          attributes: [],
        },
        accessGroups: {
          name: "accessGroups",
          isArray: true,
          type: "String",
          isRequired: false,
          attributes: [],
          isArrayNullable: true,
        },
        createdAt: {
          name: "createdAt",
          isArray: false,
          type: "AWSDateTime",
          isRequired: false,
          attributes: [],
          isReadOnly: true,
        },
        updatedAt: {
          name: "updatedAt",
          isArray: false,
          type: "AWSDateTime",
          isRequired: false,
          attributes: [],
          isReadOnly: true,
        },
      },
      syncable: true,
      pluralName: "Orders",
      attributes: [
        {
          type: "model",
          properties: {},
        },
        {
          type: "auth",
          properties: {
            rules: [
              {
                provider: "userPools",
                ownerField: "owner",
                allow: "owner",
                identityClaim: "cognito:username",
                operations: ["create", "update", "delete", "read"],
              },
              {
                groupClaim: "cognito:groups",
                provider: "userPools",
                allow: "groups",
                groups: ["Admin"],
                operations: ["create", "update", "delete", "read"],
              },
              {
                groupClaim: "cognito:groups",
                provider: "userPools",
                allow: "groups",
                groupsField: "accessGroups",
                groupField: "groups",
                operations: ["create", "update", "delete", "read"],
              },
            ],
          },
        },
      ],
    },
    Todo: {
      name: "Todo",
      fields: {
        id: {
          name: "id",
          isArray: false,
          type: "ID",
          isRequired: true,
          attributes: [],
        },
        name: {
          name: "name",
          isArray: false,
          type: "String",
          isRequired: true,
          attributes: [],
        },
        description: {
          name: "description",
          isArray: false,
          type: "String",
          isRequired: false,
          attributes: [],
        },
        createdAt: {
          name: "createdAt",
          isArray: false,
          type: "AWSDateTime",
          isRequired: false,
          attributes: [],
          isReadOnly: true,
        },
        updatedAt: {
          name: "updatedAt",
          isArray: false,
          type: "AWSDateTime",
          isRequired: false,
          attributes: [],
          isReadOnly: true,
        },
      },
      syncable: true,
      pluralName: "Todos",
      attributes: [
        {
          type: "model",
          properties: {},
        },
        {
          type: "auth",
          properties: {
            rules: [
              {
                allow: "private",
                operations: ["create", "update", "delete", "read"],
              },
            ],
          },
        },
      ],
    },
  },
  enums: {
    GiftType: {
      name: "GiftType",
      values: ["ONE_TIME", "RECURRING"],
    },
    GiftDateType: {
      name: "GiftDateType",
      values: ["BIRTHDAY", "ANNIVERSARY"],
    },
  },
  nonModels: {},
  version: "5b4d3c199131d354f9453c9d21992eab",
};
